-- MySQL Script generated by MySQL Workbench
-- 11/13/14 21:55:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ticket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ticket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticket` DEFAULT CHARACTER SET utf8 ;
USE `ticket` ;

-- -----------------------------------------------------
-- Table `ticket`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`categoria` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeCategoria` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ticket`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ticket`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`evento` (
  `idevento` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeEvento` VARCHAR(45) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `horario` VARCHAR(45) NULL DEFAULT NULL,
  `preco` VARCHAR(45) NULL DEFAULT NULL,
  `categoria_idcategoria` INT(11) NOT NULL,
  PRIMARY KEY (`idevento`),
  INDEX `fk_evento_categoria1_idx` (`categoria_idcategoria` ASC),
  CONSTRAINT `fk_evento_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `ticket`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ticket`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`compra` (
  `idcompra` INT(11) NOT NULL AUTO_INCREMENT,
  `protocolo` VARCHAR(45) NULL DEFAULT NULL,
  `quantidade` VARCHAR(45) NULL DEFAULT NULL,
  `valor_total` VARCHAR(45) NULL DEFAULT NULL,
  `cliente_idcliente` INT(11) NOT NULL,
  `evento_idevento` INT(11) NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_compra_cliente_idx` (`cliente_idcliente` ASC),
  INDEX `fk_compra_evento1_idx` (`evento_idevento` ASC),
  CONSTRAINT `fk_compra_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `ticket`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_evento1`
    FOREIGN KEY (`evento_idevento`)
    REFERENCES `ticket`.`evento` (`idevento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ticket`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticket`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nmusuario` VARCHAR(45) NULL DEFAULT NULL,
  `dssenha` VARCHAR(45) NULL DEFAULT NULL,
  `fgstatus` VARCHAR(45) NULL DEFAULT NULL,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `perfil` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
